version: 2.1

defaults: &defaults
  working_directory: /app
  docker:
    - image: golang:1.12

jobs:
  dep:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
      - run:
          name: Test
          command: make test

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build a container and push to Docker Hub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t zatsubun/go-cmnt-eol-lint:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push zatsubun/go-cmnt-eol-lint:$TAG

workflows:
  version: 2
  build-workflow:
    jobs:
      - dep:
          filters:
            branches:
              only: /.*/
      - test:
          requires:
            - dep
          filters:
            branches:
              only: /.*/
      - build:
          requires:
            - dep
            - test
          context: org-global
          filters:
            branches:
              only: /.*/
