version: 2.1

defaults: &defaults
  working_directory: /app
  docker:
    - image: golang:1.12

jobs:
  dep:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
      - run:
          name: Test
          command: make test

  build:
    <<: *defaults
    steps:
       - setup_remote_docker
       - run: |
           TAG=0.1.$CIRCLE_BUILD_NUM
           docker build -t zatsubun/go-cmnt-eol-lint:$TAG .
           docker login -u $DOCKER_USER -p $DOCKER_PASS
           docker push zatsubun/go-cmnt-eol-lint:$TAG

workflows:
  version: 2
  build-workflow:
    jobs:
      - dep:
          filters:
            branches:
              only: /.*/
      - test:
          requires:
            - dep
          filters:
            branches:
              only: /.*/
      - build:
          requires:
            - dep
            - test
          context: org-global
          filters:
            branches:
              only: /.*/
