version: 2.1

defaults: &defaults
  working_directory: /app
  docker:
    - image: golang:1.12

jobs:
  dep:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-gosum-{{ checksum "go.sum" }}
      - run:
          name: Test
          command: make test

workflows:
  version: 2
  build-workflow:
    jobs:
      - dep:
          filters:
            branches:
              only: /.*/
      - test:
          requires:
            - dep
          filters:
            branches:
              only: /.*/
